development:
  adapter: postgresql
  database: volunteeria_donate
  username: volunteeria
  password: volunteeria
  host: /var/run/postgresql
  port: 5432
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: volunteeria_donate
  username: volunteeria
  password: volunteeria
  host: /var/run/postgresql
  port: 5432
  pool: 5
  timeout: 5000

